---
name: Publish Docker Image (main)

on:
  push:
    branches:
      - 'main'
    # NOTE(canardleteer): I can't quite tell why this doesn't work yet. I intend to fix it.
    # tags:
    #   - 'v**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_REPO }}
      
      # NOTE(canardleteer): I should probably add a matrix for CUDA versions,
      #                     possibly Ubuntu versions, static for now.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AUDIOCRAFT_REF=${{ github.ref_name }}
            CUDA_VERSION=12.0.0
            UBUNTU_VERSION=22.04
             
  